# 01 - Data Import & Initial Data Exploration

In [1]:
from pymongo import MongoClient
import pandas as pd
import os
from dotenv import load_dotenv

load_dotenv()  # reads ../.env
# to keep the password out of this notebook/GitHub

#import the full database
uri = "mongodb://" + str(os.getenv("MONGO_USER")) + ":" + str(os.getenv("MONGO_PASSWORD")) + "@127.0.0.1:27019/nexus?authSource=admin"

client = MongoClient(uri)
db = client["nexus"] #stored the database in db

print(db.list_collection_names())

['boxfolders', 'htmltemplates', 'rostersizes', 'proctors', 'registrationreminders', 'accesserrors', 'finalgrades', 'tmp_math112_114_115_withdrawn_completed', 'moodlestudents', 'qualtricssurveys', 'mathablemaps', 'emails', 'mapreduce', 'lmssystems', 'registrations', 'moodlegrades', 'mailhog', 'sessions', 'mathablegrades', 'lmsgrades', 'accesslogs', 'netmathgrades', 'gradingscales', 'tmp_students', 'grades', 'tmp_roster_export', 'summer2021proctorUcodes', 'jobs', 'sites', 'headcountaverages', 'appointments', 'dropcourses', 'tokens', 'users', 'comments', 'headcounts', 'courses', 'examgrades', 'system.views', 'mentors', 'students', 'headcount2', 'netmathgradesWithAuthor', 'netmathgrades.duplicates', 'students-rostersizes', 'feedback-pending', 'students.geocode-missing', 'feedback-missing', 'students.rosters', 'students.headcounts', 'students.legal-name']

In [2]:
#explore 'students' first
students = db["students"]

df_students = pd.DataFrame(list(students.find()))
df_students.head()

,_id,crn,netId,term,mentor,filemaker,mathable,endDate,startDate,enrollDate,...,preCheck,personal,section,enrolled,moodle,set,emails,test,proctorUAccessCode,prairieLearn
0,57661210c061892a5cd0d264,10134.0,nmalajm2,120167.0,"{'comments': [], 'lastEmailDate': None, 'netId...",{'recid': 14943},"{'lastAssignment': {}, 'progress': {}, 'endDat...",2015-12-28 06:00:00,2015-09-08 05:00:00,2015-08-25 05:00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,57661210c061892a5cd0d265,10134.0,alhusan2,120167.0,"{'comments': [], 'lastEmailDate': None, 'netId...",{'recid': 14944},"{'lastAssignment': {}, 'progress': {}, 'endDat...",2015-12-28 06:00:00,2015-09-08 05:00:00,2015-08-25 05:00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,57661210c061892a5cd0d266,10107.0,screger2,120167.0,"{'comments': [], 'lastEmailDate': None, 'netId...",{'recid': 14945},"{'lastAssignment': {}, 'progress': {}, 'endDat...",2016-05-25 05:00:00,2015-08-25 05:00:00,2015-08-25 05:00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,57661210c061892a5cd0d267,10147.0,jwgunde2,120167.0,"{'comments': [], 'lastEmailDate': None, 'netId...",{'recid': 14946},"{'lastAssignment': {}, 'progress': {}, 'endDat...",2016-02-29 06:00:00,2015-09-15 05:00:00,2015-09-01 05:00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,57661210c061892a5cd0d268,10133.0,imiola2,120167.0,"{'comments': [], 'lastEmailDate': None, 'netId...",{'recid': 14947},"{'lastAssignment': {}, 'progress': {}, 'endDat...",2015-12-28 06:00:00,2015-09-08 05:00:00,2015-08-25 05:00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
print(df_students.columns.tolist())

['_id', 'crn', 'netId', 'term', 'mentor', 'filemaker', 'mathable', 'endDate', 'startDate', 'enrollDate', 'isContract', 'isAdult', 'format', 'course', 'status', 'address', 'phones', 'defunctEmails', 'otherEmails', 'email', 'uin', 'name', 'created', 'version', '__v', 'gradingScale', 'activationCode', 'welcomeEmail', 'boxFolder', 'finalGrade', 'creditHours', 'courseOrientation', 'tags', 'coordinator', 'extensions', 'grades', 'notifications', 'proctor', 'location', 'isPartner', 'subject', 'isCurrent', 'roster', 'flagged', 'completeDate', 'legalName', 'accommodation', 'inactiveEmail', 'finalExam', 'withdrawDate', 'hasCompletedQualtricsSurvey', 'preCheck', 'personal', 'section', 'enrolled', 'moodle', 'set', 'emails', 'test', 'proctorUAccessCode', 'prairieLearn']

In [4]:
df_students.dtypes

_id                    object
crn                   float64
netId                  object
term                  float64
mentor                 object
                       ...
set                    object
emails                 object
test                  float64
proctorUAccessCode     object
prairieLearn           object
Length: 61, dtype: object

In [5]:
df_students.shape

(28639, 61)

In [6]:
df_students.isna().sum()

_id                       0
crn                    7746
netId                     0
term                      1
mentor                    0
                      ...
set                   28637
emails                28637
test                  28639
proctorUAccessCode    28382
prairieLearn          28283
Length: 61, dtype: int64

In [7]:
print(df_students["_id"].nunique())
print(len(df_students))
print(df_students["netId"].duplicated().sum())
print(df_students["netId"].nunique())

28639
28639
6109
22530

In [8]:
df_students["isAdult"].value_counts(dropna=False)

isAdult
True     21998
False     6641
Name: count, dtype: int64

In [9]:
print(df_students["isAdult"].isna().sum())
print(df_students["isAdult"].dtype)

0
bool

In [10]:
df_students["finalGrade"].head()

0    5894715808473c107a54b854
1                         NaN
2    5894715808473c107a54b855
3    5894715808473c107a54b856
4                         NaN
Name: finalGrade, dtype: object

In [11]:
grades_all = db["grades"]
df_grades = pd.DataFrame(list(grades_all.find()))

df_grades.head()

,_id,author,grade,parent,created,__v,score
0,5894e14fd642c1af409b25c8,572ccde5858f41e73eb9d11d,A-,"{'kind': 'FinalGrade', 'item': 5894da0dd642c1a...",2017-02-03 19:29:17.563,0,NaN
1,589cabcb1c435941605fda0f,572ccde5858f41e73eb9d11d,B+,"{'kind': 'FinalGrade', 'item': 589ca9c21c43594...",2017-02-09 17:41:22.735,0,NaN
2,58a33662f27b098576c23bd1,572ccde5858f41e73eb9d11d,B,"{'kind': 'FinalGrade', 'item': 58a3365ef27b098...",2017-02-14 16:54:54.102,0,NaN
3,58a4c6e40bd0d0cc7eeb0a0d,572ccde5858f41e73eb9d11d,A,"{'kind': 'FinalGrade', 'item': 58a4c6e00bd0d0c...",2017-02-15 21:23:44.827,0,NaN
4,58a4cc4e0bd0d0cc7eeb0a10,572ccde5858f41e73eb9d11d,A,"{'kind': 'FinalGrade', 'item': 58a4cc490bd0d0c...",2017-02-15 21:46:49.306,0,NaN

In [12]:
finalgrades_all = db["finalgrades"]
df_finalgrades = pd.DataFrame(list(finalgrades_all.find()))

df_finalgrades.head()

,_id,student,grade,author,created,__v,boxFiles,comment,submitted,lastAttendance
0,5894715808473c107a54b846,57661210c061892a5cd0d245,A-,572ccde5858f41e73eb9d11d,2016-02-05 06:00:00,0,NaN,NaN,NaN,NaN
1,5894715808473c107a54b847,57661210c061892a5cd0d24d,C,572ccde5858f41e73eb9d11d,2016-02-29 06:00:00,0,NaN,NaN,NaN,NaN
2,5894715808473c107a54b848,57661210c061892a5cd0d23f,C,572ccde5858f41e73eb9d11d,2016-02-17 06:00:00,0,NaN,NaN,NaN,NaN
3,5894715808473c107a54b849,57661210c061892a5cd0d248,A-,572ccde5858f41e73eb9d11d,2016-05-31 05:00:00,0,NaN,NaN,NaN,NaN
4,5894715808473c107a54b84a,57661210c061892a5cd0d250,F,572ccde5858f41e73eb9d11d,2016-05-24 05:00:00,0,NaN,NaN,NaN,NaN

In [13]:
df_students["finalGrade"]

0        5894715808473c107a54b854
1                             NaN
2        5894715808473c107a54b855
3        5894715808473c107a54b856
4                             NaN
                   ...
28634                         NaN
28635                         NaN
28636                         NaN
28637                         NaN
28638                         NaN
Name: finalGrade, Length: 28639, dtype: object

In [14]:
finalgrade_ids = df_students["finalGrade"].dropna().tolist()

In [15]:
grades_data = list(
    grades_all.find({
        "_id": {"$in": finalgrade_ids}
    })
)

Find some information that could merge to current df_student dataframe:
1. "sites" - "name" (The name of the school/college/university the registered student belongs to)
2. "grades" - "grade" (Student's letter grade received in NetMath course)
3. "grades" - "parent" - "kind" (Student's received grade type, e.g. FinalGrade)